const DEFAULT_CANDIDATE_APP_URL = "http://localhost:3001";
const DEFAULT_RECRUITER_APP_URL = "http://localhost:3000";

export const CANDIDATE_APP_URL =
  process.env.NEXT_PUBLIC_CANDIDATE_APP_URL ?? DEFAULT_CANDIDATE_APP_URL;

export const RECRUITER_APP_URL =
  process.env.NEXT_PUBLIC_RECRUITER_APP_URL ?? DEFAULT_RECRUITER_APP_URL;
